services:
    rabbitmq:
        image: "rabbitmq:3-management-alpine"
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "status"]
            interval: 10s
            timeout: 10s
            retries: 5
    postgres:
        image: "postgres:13-alpine"
        environment:
            - POSTGRES_PASSWORD
        ports:
            - 5432:5432
        volumes:
            - ./init/database.sql:/docker-entrypoint-initdb.d/database.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 10s
            retries: 5
    redis:
        image: "redis:6-alpine"
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
    backend:
        container_name: microservice_backend
        build:
            context: .
            dockerfile: backend.Dockerfile
        env_file:
            - .env
        stdin_open: true
        tty: true
        depends_on:
            rabbitmq:
                condition: service_healthy
    database:
        container_name: microservice_database
        build:
            context: .
            dockerfile: database.Dockerfile
        env_file:
            - .env
        depends_on:
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_healthy
    cache:
        container_name: microservice_cache
        build:
            context: .
            dockerfile: cache.Dockerfile
        env_file:
            - .env
        depends_on:
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy

networks:
    default:
        name: messengers_ms_network
